### ISSUE TITLE
Publish an opam package?

### ISSUE THREAD

**Issue by whitequark** [ocaml/oasis2debian#1]
It would be nice if I could install oasis2debian via opam.

**Comment by edwintorok** [comment]
I have a draft opam file (generated with `oasis2opam --local`): https://github.com/edwintorok/oasis2debian/tree/opam

~~Before I can send a pull request it requires~~:
- [x] [xstrp4 META fix](https://github.com/ocaml/opam-repository/pull/4074)
- [x] opam package for [debian-formats](https://github.com/gildor478/ocaml-debian-formats)

~~After the xstrp4 fix is merged~~ you can test this with:

```
opam pin add -y debian-formats https://github.com/gildor478/ocaml-debian-formats.git
opam pin add -y oasis2debian 'https://github.com/edwintorok/oasis2debian.git#opam'
```

If these package pins work properly then the package could be added to the proper opam repo too.
