### ISSUE TITLE
Can't install from opam because of xstrp4

### ISSUE THREAD

**Issue by redianthus** [ocaml/oasis2debian#3]
Hi,

On a `4.06.1` switch, it's not possible to install `oasis2debian` as the compilation of `xstrp4` fails. It seems to be outdated.

**Comment by gildor478** [comment]
Do you know if there is any plan to upgrade xstrp4?

**Comment by redianthus** [comment]
I have no idea about it, but the last commit is 2 years old according to [this repo](https://gitlab.camlcity.org/gerd/lib-xstrp4).

**Comment by gildor478** [comment]
I think it is time to get rid of xstrp4 and to find something easier to maintain. It will take time, given my current workload.

**Comment by gildor478** [comment]
This is fixed in d971e72b07201fe9d2d9dc834489bb8878af8d34.

PR for opam:
ocaml/opam-repository#11726
